[2025-08-18T13:22:12.447+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T13:22:12.744+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_05_tags_core_metrics manual__2025-08-18T13:16:17.589887+00:00 [queued]>
[2025-08-18T13:22:12.819+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_05_tags_core_metrics manual__2025-08-18T13:16:17.589887+00:00 [queued]>
[2025-08-18T13:22:12.820+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2025-08-18T13:22:12.995+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_q_05_tags_core_metrics> on 2025-08-18 13:16:17.589887+00:00
[2025-08-18T13:22:13.055+0000] {standard_task_runner.py:63} INFO - Started process 4878 to run task
[2025-08-18T13:22:13.071+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'run_q_05_tags_core_metrics', 'manual__2025-08-18T13:16:17.589887+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpeh_lijb4']
[2025-08-18T13:22:13.079+0000] {standard_task_runner.py:91} INFO - Job 288: Subtask run_q_05_tags_core_metrics
[2025-08-18T13:22:13.399+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.run_q_05_tags_core_metrics manual__2025-08-18T13:16:17.589887+00:00 [running]> on host 47205959681c
[2025-08-18T13:22:13.865+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='run_q_05_tags_core_metrics' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T13:16:17.589887+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T13:16:17.589887+00:00'
[2025-08-18T13:22:13.866+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T13:22:13.914+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T13:22:13.916+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=citus psql -h citus_coordinator -U citus -d youtube_dw -f /opt/***/sql/q_05_tags_core_metrics']
[2025-08-18T13:22:13.958+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T13:22:14.145+0000] {subprocess.py:93} INFO - psql: error: /opt/***/sql/q_05_tags_core_metrics: No such file or directory
[2025-08-18T13:22:14.146+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-18T13:22:14.147+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T13:22:14.228+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-18T13:22:14.242+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=run_q_05_tags_core_metrics, execution_date=20250818T131617, start_date=20250818T132212, end_date=20250818T132214
[2025-08-18T13:22:14.337+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 288 for task run_q_05_tags_core_metrics (Bash command failed. The command returned a non-zero exit code 1.; 4878)
[2025-08-18T13:22:14.361+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T13:22:14.602+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T13:22:14.603+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
