[2025-08-18T11:31:06.348+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: youtube_pipeline_simple.transform_golden manual__2025-08-18T11:28:59.532098+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
