[2025-08-18T10:13:50.256+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T10:13:50.339+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_simple.golden_to_star manual__2025-08-18T10:05:46.897943+00:00 [queued]>
[2025-08-18T10:13:50.360+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_simple.golden_to_star manual__2025-08-18T10:05:46.897943+00:00 [queued]>
[2025-08-18T10:13:50.360+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-08-18T10:13:50.394+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): golden_to_star> on 2025-08-18 10:05:46.897943+00:00
[2025-08-18T10:13:50.412+0000] {standard_task_runner.py:63} INFO - Started process 2133 to run task
[2025-08-18T10:13:50.419+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_simple', 'golden_to_star', 'manual__2025-08-18T10:05:46.897943+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpqxqvq2vk']
[2025-08-18T10:13:50.424+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask golden_to_star
[2025-08-18T10:13:50.535+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_simple.golden_to_star manual__2025-08-18T10:05:46.897943+00:00 [running]> on host 47205959681c
[2025-08-18T10:13:50.776+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_simple' AIRFLOW_CTX_TASK_ID='golden_to_star' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T10:05:46.897943+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T10:05:46.897943+00:00'
[2025-08-18T10:13:50.781+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T10:13:50.816+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T10:13:50.819+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec youtube-pipeline-project_spark-master_1 spark-submit --master spark://spark-master:7077 --deploy-mode client --packages org.postgresql:postgresql:42.6.0 /opt/***/jobs/star_schema/golden_to_star_citus.py']
[2025-08-18T10:13:50.841+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T10:14:01.026+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-08-18T10:14:01.188+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-08-18T10:14:01.189+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-08-18T10:14:01.211+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-08-18T10:14:01.213+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-f3a7a3e9-cb5b-4a0b-a695-72af85d6506c;1.0
[2025-08-18T10:14:01.220+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-08-18T10:14:05.186+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-08-18T10:14:05.755+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-08-18T10:14:05.937+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar ...
[2025-08-18T10:14:06.249+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.postgresql#postgresql;42.6.0!postgresql.jar (339ms)
[2025-08-18T10:14:06.281+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.31.0/checker-qual-3.31.0.jar ...
[2025-08-18T10:14:06.429+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.checkerframework#checker-qual;3.31.0!checker-qual.jar (182ms)
[2025-08-18T10:14:06.449+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 4688ms :: artifacts dl 546ms
[2025-08-18T10:14:06.450+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-08-18T10:14:06.453+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-08-18T10:14:06.455+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-08-18T10:14:06.455+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-08-18T10:14:06.456+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-08-18T10:14:06.465+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-08-18T10:14:06.467+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-08-18T10:14:06.468+0000] {subprocess.py:93} INFO - 	|      default     |   2   |   2   |   2   |   0   ||   2   |   2   |
[2025-08-18T10:14:06.468+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-08-18T10:14:06.477+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-f3a7a3e9-cb5b-4a0b-a695-72af85d6506c
[2025-08-18T10:14:06.478+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-08-18T10:14:06.497+0000] {subprocess.py:93} INFO - 	2 artifacts copied, 0 already retrieved (1274kB/20ms)
[2025-08-18T10:14:08.266+0000] {subprocess.py:93} INFO - 25/08/18 10:14:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-18T10:14:12.825+0000] {subprocess.py:93} INFO - 25/08/18 10:14:12 INFO SparkContext: Running Spark version 3.5.1
[2025-08-18T10:14:12.828+0000] {subprocess.py:93} INFO - 25/08/18 10:14:12 INFO SparkContext: OS info Linux, 6.11.0-29-generic, amd64
[2025-08-18T10:14:12.834+0000] {subprocess.py:93} INFO - 25/08/18 10:14:12 INFO SparkContext: Java version 17.0.12
[2025-08-18T10:14:12.974+0000] {subprocess.py:93} INFO - 25/08/18 10:14:12 INFO ResourceUtils: ==============================================================
[2025-08-18T10:14:12.976+0000] {subprocess.py:93} INFO - 25/08/18 10:14:12 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-18T10:14:12.976+0000] {subprocess.py:93} INFO - 25/08/18 10:14:12 INFO ResourceUtils: ==============================================================
[2025-08-18T10:14:12.976+0000] {subprocess.py:93} INFO - 25/08/18 10:14:12 INFO SparkContext: Submitted application: Golden to Star Schema in Citus
[2025-08-18T10:14:13.026+0000] {subprocess.py:93} INFO - 25/08/18 10:14:13 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-18T10:14:13.057+0000] {subprocess.py:93} INFO - 25/08/18 10:14:13 INFO ResourceProfile: Limiting resource is cpu
[2025-08-18T10:14:13.061+0000] {subprocess.py:93} INFO - 25/08/18 10:14:13 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-18T10:14:13.213+0000] {subprocess.py:93} INFO - 25/08/18 10:14:13 INFO SecurityManager: Changing view acls to: spark
[2025-08-18T10:14:13.215+0000] {subprocess.py:93} INFO - 25/08/18 10:14:13 INFO SecurityManager: Changing modify acls to: spark
[2025-08-18T10:14:13.221+0000] {subprocess.py:93} INFO - 25/08/18 10:14:13 INFO SecurityManager: Changing view acls groups to:
[2025-08-18T10:14:13.222+0000] {subprocess.py:93} INFO - 25/08/18 10:14:13 INFO SecurityManager: Changing modify acls groups to:
[2025-08-18T10:14:13.224+0000] {subprocess.py:93} INFO - 25/08/18 10:14:13 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: spark; groups with view permissions: EMPTY; users with modify permissions: spark; groups with modify permissions: EMPTY
[2025-08-18T10:14:14.067+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO Utils: Successfully started service 'sparkDriver' on port 33715.
[2025-08-18T10:14:14.136+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO SparkEnv: Registering MapOutputTracker
[2025-08-18T10:14:14.206+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-18T10:14:14.246+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-18T10:14:14.249+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-18T10:14:14.258+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-18T10:14:14.299+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a6daaf69-7942-46b4-a867-ed42ee4bccfe
[2025-08-18T10:14:14.368+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-08-18T10:14:14.439+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-18T10:14:14.780+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-08-18T10:14:14.935+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-08-18T10:14:14.953+0000] {subprocess.py:93} INFO - 25/08/18 10:14:14 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2025-08-18T10:14:15.126+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO SparkContext: Added JAR file:///opt/bitnami/spark/.ivy2/jars/org.postgresql_postgresql-42.6.0.jar at spark://4bf6b336ccb3:33715/jars/org.postgresql_postgresql-42.6.0.jar with timestamp 1755512052796
[2025-08-18T10:14:15.127+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO SparkContext: Added JAR file:///opt/bitnami/spark/.ivy2/jars/org.checkerframework_checker-qual-3.31.0.jar at spark://4bf6b336ccb3:33715/jars/org.checkerframework_checker-qual-3.31.0.jar with timestamp 1755512052796
[2025-08-18T10:14:15.141+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO SparkContext: Added file file:///opt/bitnami/spark/.ivy2/jars/org.postgresql_postgresql-42.6.0.jar at spark://4bf6b336ccb3:33715/files/org.postgresql_postgresql-42.6.0.jar with timestamp 1755512052796
[2025-08-18T10:14:15.148+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO Utils: Copying /opt/bitnami/spark/.ivy2/jars/org.postgresql_postgresql-42.6.0.jar to /tmp/spark-65dad7b2-68ec-4c48-9c04-0406ac71ee0e/userFiles-8a2d6d70-67b7-48e3-ac68-efd97567589d/org.postgresql_postgresql-42.6.0.jar
[2025-08-18T10:14:15.186+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO SparkContext: Added file file:///opt/bitnami/spark/.ivy2/jars/org.checkerframework_checker-qual-3.31.0.jar at spark://4bf6b336ccb3:33715/files/org.checkerframework_checker-qual-3.31.0.jar with timestamp 1755512052796
[2025-08-18T10:14:15.197+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO Utils: Copying /opt/bitnami/spark/.ivy2/jars/org.checkerframework_checker-qual-3.31.0.jar to /tmp/spark-65dad7b2-68ec-4c48-9c04-0406ac71ee0e/userFiles-8a2d6d70-67b7-48e3-ac68-efd97567589d/org.checkerframework_checker-qual-3.31.0.jar
[2025-08-18T10:14:15.440+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-08-18T10:14:15.546+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.7:7077 after 67 ms (0 ms spent in bootstraps)
[2025-08-18T10:14:15.729+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250818101415-0007
[2025-08-18T10:14:15.748+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46681.
[2025-08-18T10:14:15.750+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO NettyBlockTransferService: Server created on 4bf6b336ccb3:46681
[2025-08-18T10:14:15.755+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-18T10:14:15.769+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 4bf6b336ccb3, 46681, None)
[2025-08-18T10:14:15.775+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO BlockManagerMasterEndpoint: Registering block manager 4bf6b336ccb3:46681 with 434.4 MiB RAM, BlockManagerId(driver, 4bf6b336ccb3, 46681, None)
[2025-08-18T10:14:15.782+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 4bf6b336ccb3, 46681, None)
[2025-08-18T10:14:15.783+0000] {subprocess.py:93} INFO - 25/08/18 10:14:15 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 4bf6b336ccb3, 46681, None)
[2025-08-18T10:14:16.475+0000] {subprocess.py:93} INFO - 25/08/18 10:14:16 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-08-18T10:14:16.872+0000] {subprocess.py:93} INFO - 25/08/18 10:14:16 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-08-18T10:14:16.877+0000] {subprocess.py:93} INFO - 25/08/18 10:14:16 INFO SharedState: Warehouse path is 'file:/opt/bitnami/spark/spark-warehouse'.
[2025-08-18T10:14:20.464+0000] {subprocess.py:93} INFO - 25/08/18 10:14:20 INFO InMemoryFileIndex: It took 576 ms to list leaf files for 1 paths.
[2025-08-18T10:14:22.171+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO SparkContext: Starting job: parquet at NativeMethodAccessorImpl.java:0
[2025-08-18T10:14:22.210+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO DAGScheduler: Got job 0 (parquet at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2025-08-18T10:14:22.211+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO DAGScheduler: Final stage: ResultStage 0 (parquet at NativeMethodAccessorImpl.java:0)
[2025-08-18T10:14:22.212+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO DAGScheduler: Parents of final stage: List()
[2025-08-18T10:14:22.214+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO DAGScheduler: Missing parents: List()
[2025-08-18T10:14:22.219+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at parquet at NativeMethodAccessorImpl.java:0), which has no missing parents
[2025-08-18T10:14:22.420+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 104.5 KiB, free 434.3 MiB)
[2025-08-18T10:14:22.569+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 37.8 KiB, free 434.3 MiB)
[2025-08-18T10:14:22.585+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 4bf6b336ccb3:46681 (size: 37.8 KiB, free: 434.4 MiB)
[2025-08-18T10:14:22.605+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[2025-08-18T10:14:22.682+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at parquet at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2025-08-18T10:14:22.686+0000] {subprocess.py:93} INFO - 25/08/18 10:14:22 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2025-08-18T10:14:37.736+0000] {subprocess.py:93} INFO - 25/08/18 10:14:37 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-08-18T10:14:52.741+0000] {subprocess.py:93} INFO - 25/08/18 10:14:52 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-08-18T10:15:07.737+0000] {subprocess.py:93} INFO - 25/08/18 10:15:07 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-08-18T10:15:22.735+0000] {subprocess.py:93} INFO - 25/08/18 10:15:22 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-08-18T10:15:37.738+0000] {subprocess.py:93} INFO - 25/08/18 10:15:37 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-08-18T10:15:52.744+0000] {subprocess.py:93} INFO - 25/08/18 10:15:52 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-08-18T10:16:02.206+0000] {subprocess.py:93} INFO - 25/08/18 10:16:02 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250818101415-0007/0 on worker-20250818100309-172.18.0.14-34047 (172.18.0.14:34047) with 4 core(s)
[2025-08-18T10:16:02.214+0000] {subprocess.py:93} INFO - 25/08/18 10:16:02 INFO StandaloneSchedulerBackend: Granted executor ID app-20250818101415-0007/0 on hostPort 172.18.0.14:34047 with 4 core(s), 1024.0 MiB RAM
[2025-08-18T10:16:02.254+0000] {subprocess.py:93} INFO - 25/08/18 10:16:02 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250818101415-0007/1 on worker-20250818100311-172.18.0.13-33759 (172.18.0.13:33759) with 4 core(s)
[2025-08-18T10:16:02.255+0000] {subprocess.py:93} INFO - 25/08/18 10:16:02 INFO StandaloneSchedulerBackend: Granted executor ID app-20250818101415-0007/1 on hostPort 172.18.0.13:33759 with 4 core(s), 1024.0 MiB RAM
[2025-08-18T10:16:02.256+0000] {subprocess.py:93} INFO - 25/08/18 10:16:02 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250818101415-0007/2 on worker-20250818100314-172.18.0.12-34745 (172.18.0.12:34745) with 4 core(s)
[2025-08-18T10:16:02.259+0000] {subprocess.py:93} INFO - 25/08/18 10:16:02 INFO StandaloneSchedulerBackend: Granted executor ID app-20250818101415-0007/2 on hostPort 172.18.0.12:34745 with 4 core(s), 1024.0 MiB RAM
[2025-08-18T10:16:02.717+0000] {subprocess.py:93} INFO - 25/08/18 10:16:02 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250818101415-0007/2 is now RUNNING
[2025-08-18T10:16:02.767+0000] {subprocess.py:93} INFO - 25/08/18 10:16:02 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250818101415-0007/0 is now RUNNING
[2025-08-18T10:16:02.805+0000] {subprocess.py:93} INFO - 25/08/18 10:16:02 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250818101415-0007/1 is now RUNNING
[2025-08-18T10:16:07.741+0000] {subprocess.py:93} INFO - 25/08/18 10:16:07 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-08-18T10:16:19.844+0000] {subprocess.py:93} INFO - 25/08/18 10:16:19 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.13:59022) with ID 1,  ResourceProfileId 0
[2025-08-18T10:16:20.124+0000] {subprocess.py:93} INFO - 25/08/18 10:16:20 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.12:44334) with ID 2,  ResourceProfileId 0
[2025-08-18T10:16:20.228+0000] {subprocess.py:93} INFO - 25/08/18 10:16:20 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.13:41109 with 434.4 MiB RAM, BlockManagerId(1, 172.18.0.13, 41109, None)
[2025-08-18T10:16:20.311+0000] {subprocess.py:93} INFO - 25/08/18 10:16:20 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.14:42278) with ID 0,  ResourceProfileId 0
[2025-08-18T10:16:20.717+0000] {subprocess.py:93} INFO - 25/08/18 10:16:20 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.14:40073 with 434.4 MiB RAM, BlockManagerId(0, 172.18.0.14, 40073, None)
[2025-08-18T10:16:20.860+0000] {subprocess.py:93} INFO - 25/08/18 10:16:20 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.12:39203 with 434.4 MiB RAM, BlockManagerId(2, 172.18.0.12, 39203, None)
[2025-08-18T10:16:21.315+0000] {subprocess.py:93} INFO - 25/08/18 10:16:21 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.18.0.13, executor 1, partition 0, PROCESS_LOCAL, 8298 bytes)
[2025-08-18T10:16:22.628+0000] {subprocess.py:93} INFO - 25/08/18 10:16:22 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.18.0.13:41109 (size: 37.8 KiB, free: 434.4 MiB)
[2025-08-18T10:16:25.786+0000] {subprocess.py:93} INFO - 25/08/18 10:16:25 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (172.18.0.13 executor 1): org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-08-18T10:16:25.787+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-08-18T10:16:25.788+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-08-18T10:16:25.788+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:387)
[2025-08-18T10:16:25.789+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-08-18T10:16:25.789+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-08-18T10:16:25.790+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-08-18T10:16:25.794+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:80)
[2025-08-18T10:16:25.794+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:858)
[2025-08-18T10:16:25.795+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:858)
[2025-08-18T10:16:25.795+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-08-18T10:16:25.796+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-08-18T10:16:25.798+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-08-18T10:16:25.800+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-08-18T10:16:25.800+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-08-18T10:16:25.801+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-08-18T10:16:25.801+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-08-18T10:16:25.802+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-08-18T10:16:25.805+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-08-18T10:16:25.805+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-08-18T10:16:25.805+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-08-18T10:16:25.806+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-08-18T10:16:25.806+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-08-18T10:16:25.806+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-08-18T10:16:25.810+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /storage/hdfs/processed/golden_dataset/part-00000-db1a0cbd-e62a-41da-949d-a5692fdcd3ed-c000.snappy.parquet
[2025-08-18T10:16:25.811+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-08-18T10:16:25.813+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-08-18T10:16:25.815+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
[2025-08-18T10:16:25.816+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1954)
[2025-08-18T10:16:25.817+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
[2025-08-18T10:16:25.817+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
[2025-08-18T10:16:25.818+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-08-18T10:16:25.818+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-08-18T10:16:25.818+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-08-18T10:16:25.823+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-08-18T10:16:25.824+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-08-18T10:16:25.824+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-08-18T10:16:25.825+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-08-18T10:16:25.825+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-08-18T10:16:25.825+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-08-18T10:16:25.830+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:25.832+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-08-18T10:16:25.833+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-08-18T10:16:25.833+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-08-18T10:16:25.833+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-08-18T10:16:25.837+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-08-18T10:16:25.837+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-08-18T10:16:25.838+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-08-18T10:16:25.843+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-08-18T10:16:25.843+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-08-18T10:16:25.844+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-08-18T10:16:25.846+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-08-18T10:16:25.847+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-08-18T10:16:25.847+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-08-18T10:16:25.847+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-08-18T10:16:25.854+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-08-18T10:16:25.855+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-08-18T10:16:25.855+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-08-18T10:16:25.856+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-08-18T10:16:25.856+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-08-18T10:16:25.856+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-08-18T10:16:25.857+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-08-18T10:16:25.857+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-08-18T10:16:25.857+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-08-18T10:16:25.858+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-08-18T10:16:25.862+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-08-18T10:16:25.863+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-08-18T10:16:25.863+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-08-18T10:16:25.864+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-08-18T10:16:25.864+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-08-18T10:16:25.864+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-08-18T10:16:25.866+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-08-18T10:16:25.867+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-08-18T10:16:25.868+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-08-18T10:16:25.869+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-08-18T10:16:25.870+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-08-18T10:16:25.871+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-08-18T10:16:25.872+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /storage/hdfs/processed/golden_dataset/part-00000-db1a0cbd-e62a-41da-949d-a5692fdcd3ed-c000.snappy.parquet
[2025-08-18T10:16:25.872+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-08-18T10:16:25.872+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-08-18T10:16:25.873+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
[2025-08-18T10:16:25.873+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1954)
[2025-08-18T10:16:25.873+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
[2025-08-18T10:16:25.874+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
[2025-08-18T10:16:25.875+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-08-18T10:16:25.876+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-08-18T10:16:25.877+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-08-18T10:16:25.879+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-08-18T10:16:25.880+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-08-18T10:16:25.881+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-08-18T10:16:25.882+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-08-18T10:16:25.883+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-08-18T10:16:25.883+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-08-18T10:16:25.885+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:25.886+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-08-18T10:16:25.888+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-08-18T10:16:25.889+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-08-18T10:16:25.889+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-08-18T10:16:25.892+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-08-18T10:16:25.892+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy31.getBlockLocations(Unknown Source)
[2025-08-18T10:16:25.893+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-08-18T10:16:25.893+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-08-18T10:16:25.893+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-08-18T10:16:25.895+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-08-18T10:16:25.896+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-08-18T10:16:25.897+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-08-18T10:16:25.897+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-08-18T10:16:25.897+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-08-18T10:16:25.901+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-08-18T10:16:25.901+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-08-18T10:16:25.902+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy32.getBlockLocations(Unknown Source)
[2025-08-18T10:16:25.902+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-08-18T10:16:25.902+0000] {subprocess.py:93} INFO - 	... 28 more
[2025-08-18T10:16:25.903+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:25.903+0000] {subprocess.py:93} INFO - 25/08/18 10:16:25 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1) (172.18.0.14, executor 0, partition 0, PROCESS_LOCAL, 8298 bytes)
[2025-08-18T10:16:26.641+0000] {subprocess.py:93} INFO - 25/08/18 10:16:26 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.18.0.14:40073 (size: 37.8 KiB, free: 434.4 MiB)
[2025-08-18T10:16:29.837+0000] {subprocess.py:93} INFO - 25/08/18 10:16:29 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on 172.18.0.14, executor 0: org.apache.spark.SparkException (Exception thrown in awaitResult: ) [duplicate 1]
[2025-08-18T10:16:29.840+0000] {subprocess.py:93} INFO - 25/08/18 10:16:29 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2) (172.18.0.13, executor 1, partition 0, PROCESS_LOCAL, 8298 bytes)
[2025-08-18T10:16:30.193+0000] {subprocess.py:93} INFO - 25/08/18 10:16:30 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2) on 172.18.0.13, executor 1: org.apache.spark.SparkException (Exception thrown in awaitResult: ) [duplicate 2]
[2025-08-18T10:16:30.207+0000] {subprocess.py:93} INFO - 25/08/18 10:16:30 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 3) (172.18.0.13, executor 1, partition 0, PROCESS_LOCAL, 8298 bytes)
[2025-08-18T10:16:30.392+0000] {subprocess.py:93} INFO - 25/08/18 10:16:30 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 3) on 172.18.0.13, executor 1: org.apache.spark.SparkException (Exception thrown in awaitResult: ) [duplicate 3]
[2025-08-18T10:16:30.402+0000] {subprocess.py:93} INFO - 25/08/18 10:16:30 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
[2025-08-18T10:16:30.414+0000] {subprocess.py:93} INFO - 25/08/18 10:16:30 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2025-08-18T10:16:30.420+0000] {subprocess.py:93} INFO - 25/08/18 10:16:30 INFO TaskSchedulerImpl: Cancelling stage 0
[2025-08-18T10:16:30.422+0000] {subprocess.py:93} INFO - 25/08/18 10:16:30 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.13 executor 1): org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-08-18T10:16:30.423+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-08-18T10:16:30.424+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-08-18T10:16:30.424+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:387)
[2025-08-18T10:16:30.424+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-08-18T10:16:30.425+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-08-18T10:16:30.426+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-08-18T10:16:30.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:80)
[2025-08-18T10:16:30.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:858)
[2025-08-18T10:16:30.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:858)
[2025-08-18T10:16:30.431+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-08-18T10:16:30.431+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-08-18T10:16:30.431+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-08-18T10:16:30.432+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-08-18T10:16:30.436+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-08-18T10:16:30.438+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-08-18T10:16:30.439+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-08-18T10:16:30.439+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-08-18T10:16:30.440+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-08-18T10:16:30.441+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-08-18T10:16:30.441+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-08-18T10:16:30.442+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-08-18T10:16:30.444+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-08-18T10:16:30.447+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-08-18T10:16:30.448+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /storage/hdfs/processed/golden_dataset/part-00000-db1a0cbd-e62a-41da-949d-a5692fdcd3ed-c000.snappy.parquet
[2025-08-18T10:16:30.448+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-08-18T10:16:30.448+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-08-18T10:16:30.450+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
[2025-08-18T10:16:30.454+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1954)
[2025-08-18T10:16:30.457+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
[2025-08-18T10:16:30.458+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
[2025-08-18T10:16:30.458+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-08-18T10:16:30.459+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-08-18T10:16:30.459+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-08-18T10:16:30.460+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-08-18T10:16:30.461+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-08-18T10:16:30.462+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-08-18T10:16:30.463+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-08-18T10:16:30.463+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-08-18T10:16:30.464+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-08-18T10:16:30.465+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:30.466+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-08-18T10:16:30.466+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-08-18T10:16:30.467+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-08-18T10:16:30.468+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-08-18T10:16:30.469+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-08-18T10:16:30.469+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-08-18T10:16:30.469+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-08-18T10:16:30.470+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-08-18T10:16:30.470+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-08-18T10:16:30.470+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-08-18T10:16:30.470+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-08-18T10:16:30.472+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-08-18T10:16:30.473+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-08-18T10:16:30.473+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-08-18T10:16:30.474+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-08-18T10:16:30.475+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-08-18T10:16:30.475+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-08-18T10:16:30.475+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-08-18T10:16:30.476+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-08-18T10:16:30.477+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-08-18T10:16:30.477+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-08-18T10:16:30.478+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-08-18T10:16:30.479+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-08-18T10:16:30.479+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-08-18T10:16:30.479+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-08-18T10:16:30.480+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-08-18T10:16:30.481+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-08-18T10:16:30.481+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-08-18T10:16:30.482+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-08-18T10:16:30.483+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-08-18T10:16:30.483+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-08-18T10:16:30.484+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-08-18T10:16:30.484+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-08-18T10:16:30.484+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-08-18T10:16:30.486+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-08-18T10:16:30.486+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-08-18T10:16:30.487+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /storage/hdfs/processed/golden_dataset/part-00000-db1a0cbd-e62a-41da-949d-a5692fdcd3ed-c000.snappy.parquet
[2025-08-18T10:16:30.488+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-08-18T10:16:30.488+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-08-18T10:16:30.489+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
[2025-08-18T10:16:30.489+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1954)
[2025-08-18T10:16:30.490+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
[2025-08-18T10:16:30.491+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
[2025-08-18T10:16:30.492+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-08-18T10:16:30.493+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-08-18T10:16:30.494+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-08-18T10:16:30.494+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-08-18T10:16:30.494+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-08-18T10:16:30.495+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-08-18T10:16:30.495+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-08-18T10:16:30.495+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-08-18T10:16:30.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-08-18T10:16:30.496+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:30.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-08-18T10:16:30.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-08-18T10:16:30.498+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-08-18T10:16:30.499+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-08-18T10:16:30.500+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-08-18T10:16:30.500+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy31.getBlockLocations(Unknown Source)
[2025-08-18T10:16:30.501+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-08-18T10:16:30.501+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-08-18T10:16:30.502+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-08-18T10:16:30.502+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-08-18T10:16:30.502+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-08-18T10:16:30.503+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-08-18T10:16:30.503+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-08-18T10:16:30.503+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-08-18T10:16:30.505+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-08-18T10:16:30.505+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-08-18T10:16:30.506+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy32.getBlockLocations(Unknown Source)
[2025-08-18T10:16:30.506+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-08-18T10:16:30.507+0000] {subprocess.py:93} INFO - 	... 28 more
[2025-08-18T10:16:30.507+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:30.507+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-08-18T10:16:30.507+0000] {subprocess.py:93} INFO - 25/08/18 10:16:30 INFO DAGScheduler: ResultStage 0 (parquet at NativeMethodAccessorImpl.java:0) failed in 128.153 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.13 executor 1): org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-08-18T10:16:30.512+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-08-18T10:16:30.512+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-08-18T10:16:30.512+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:387)
[2025-08-18T10:16:30.513+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-08-18T10:16:30.513+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-08-18T10:16:30.513+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-08-18T10:16:30.514+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:80)
[2025-08-18T10:16:30.515+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:858)
[2025-08-18T10:16:30.515+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:858)
[2025-08-18T10:16:30.516+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-08-18T10:16:30.516+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-08-18T10:16:30.516+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-08-18T10:16:30.517+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-08-18T10:16:30.517+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-08-18T10:16:30.517+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-08-18T10:16:30.518+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-08-18T10:16:30.519+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-08-18T10:16:30.520+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-08-18T10:16:30.520+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-08-18T10:16:30.521+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-08-18T10:16:30.521+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-08-18T10:16:30.522+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-08-18T10:16:30.523+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-08-18T10:16:30.523+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /storage/hdfs/processed/golden_dataset/part-00000-db1a0cbd-e62a-41da-949d-a5692fdcd3ed-c000.snappy.parquet
[2025-08-18T10:16:30.524+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-08-18T10:16:30.524+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-08-18T10:16:30.524+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
[2025-08-18T10:16:30.524+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1954)
[2025-08-18T10:16:30.526+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
[2025-08-18T10:16:30.526+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
[2025-08-18T10:16:30.526+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-08-18T10:16:30.527+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-08-18T10:16:30.527+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-08-18T10:16:30.527+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-08-18T10:16:30.529+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-08-18T10:16:30.530+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-08-18T10:16:30.530+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-08-18T10:16:30.531+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-08-18T10:16:30.531+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-08-18T10:16:30.531+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:30.531+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-08-18T10:16:30.532+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-08-18T10:16:30.532+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-08-18T10:16:30.532+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-08-18T10:16:30.534+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-08-18T10:16:30.534+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-08-18T10:16:30.534+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-08-18T10:16:30.535+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-08-18T10:16:30.535+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-08-18T10:16:30.535+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-08-18T10:16:30.536+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-08-18T10:16:30.536+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-08-18T10:16:30.536+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-08-18T10:16:30.536+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-08-18T10:16:30.537+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-08-18T10:16:30.537+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-08-18T10:16:30.537+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-08-18T10:16:30.540+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-08-18T10:16:30.541+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-08-18T10:16:30.541+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-08-18T10:16:30.541+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-08-18T10:16:30.541+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-08-18T10:16:30.542+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-08-18T10:16:30.542+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-08-18T10:16:30.543+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-08-18T10:16:30.543+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-08-18T10:16:30.543+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-08-18T10:16:30.547+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-08-18T10:16:30.548+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-08-18T10:16:30.548+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-08-18T10:16:30.549+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-08-18T10:16:30.549+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-08-18T10:16:30.550+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-08-18T10:16:30.550+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-08-18T10:16:30.550+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-08-18T10:16:30.551+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-08-18T10:16:30.551+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /storage/hdfs/processed/golden_dataset/part-00000-db1a0cbd-e62a-41da-949d-a5692fdcd3ed-c000.snappy.parquet
[2025-08-18T10:16:30.551+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-08-18T10:16:30.552+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-08-18T10:16:30.552+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
[2025-08-18T10:16:30.552+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1954)
[2025-08-18T10:16:30.552+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
[2025-08-18T10:16:30.553+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
[2025-08-18T10:16:30.553+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-08-18T10:16:30.553+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-08-18T10:16:30.554+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-08-18T10:16:30.554+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-08-18T10:16:30.555+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-08-18T10:16:30.555+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-08-18T10:16:30.555+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-08-18T10:16:30.556+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-08-18T10:16:30.557+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-08-18T10:16:30.557+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:30.557+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-08-18T10:16:30.557+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-08-18T10:16:30.558+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-08-18T10:16:30.558+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-08-18T10:16:30.558+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-08-18T10:16:30.558+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy31.getBlockLocations(Unknown Source)
[2025-08-18T10:16:30.560+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-08-18T10:16:30.561+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-08-18T10:16:30.561+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-08-18T10:16:30.563+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-08-18T10:16:30.564+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-08-18T10:16:30.564+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-08-18T10:16:30.564+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-08-18T10:16:30.565+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-08-18T10:16:30.565+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-08-18T10:16:30.565+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-08-18T10:16:30.566+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy32.getBlockLocations(Unknown Source)
[2025-08-18T10:16:30.566+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-08-18T10:16:30.567+0000] {subprocess.py:93} INFO - 	... 28 more
[2025-08-18T10:16:30.568+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:30.569+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-08-18T10:16:30.569+0000] {subprocess.py:93} INFO - 25/08/18 10:16:30 INFO DAGScheduler: Job 0 failed: parquet at NativeMethodAccessorImpl.java:0, took 128.289742 s
[2025-08-18T10:16:31.135+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-18T10:16:31.136+0000] {subprocess.py:93} INFO -   File "/opt/***/jobs/star_schema/golden_to_star_citus.py", line 33, in <module>
[2025-08-18T10:16:31.137+0000] {subprocess.py:93} INFO -     df = spark.read.parquet(golden_path)
[2025-08-18T10:16:31.137+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-18T10:16:31.137+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
[2025-08-18T10:16:31.138+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-08-18T10:16:31.139+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-08-18T10:16:31.139+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-08-18T10:16:31.182+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o28.parquet.
[2025-08-18T10:16:31.183+0000] {subprocess.py:93} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.13 executor 1): org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-08-18T10:16:31.184+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-08-18T10:16:31.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-08-18T10:16:31.189+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:387)
[2025-08-18T10:16:31.190+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-08-18T10:16:31.194+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-08-18T10:16:31.195+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-08-18T10:16:31.196+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:80)
[2025-08-18T10:16:31.197+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:858)
[2025-08-18T10:16:31.200+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:858)
[2025-08-18T10:16:31.201+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-08-18T10:16:31.202+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-08-18T10:16:31.202+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-08-18T10:16:31.202+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-08-18T10:16:31.205+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-08-18T10:16:31.208+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-08-18T10:16:31.209+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-08-18T10:16:31.210+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-08-18T10:16:31.210+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-08-18T10:16:31.211+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-08-18T10:16:31.213+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-08-18T10:16:31.214+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-08-18T10:16:31.217+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-08-18T10:16:31.218+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-08-18T10:16:31.222+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /storage/hdfs/processed/golden_dataset/part-00000-db1a0cbd-e62a-41da-949d-a5692fdcd3ed-c000.snappy.parquet
[2025-08-18T10:16:31.223+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-08-18T10:16:31.224+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-08-18T10:16:31.224+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
[2025-08-18T10:16:31.225+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1954)
[2025-08-18T10:16:31.225+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
[2025-08-18T10:16:31.225+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
[2025-08-18T10:16:31.225+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-08-18T10:16:31.229+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-08-18T10:16:31.231+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-08-18T10:16:31.231+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-08-18T10:16:31.232+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-08-18T10:16:31.232+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-08-18T10:16:31.232+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-08-18T10:16:31.238+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-08-18T10:16:31.239+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-08-18T10:16:31.241+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:31.243+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-08-18T10:16:31.244+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-08-18T10:16:31.246+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-08-18T10:16:31.248+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-08-18T10:16:31.248+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-08-18T10:16:31.252+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-08-18T10:16:31.254+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-08-18T10:16:31.256+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-08-18T10:16:31.257+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-08-18T10:16:31.259+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-08-18T10:16:31.259+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-08-18T10:16:31.260+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-08-18T10:16:31.260+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-08-18T10:16:31.260+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-08-18T10:16:31.260+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-08-18T10:16:31.261+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-08-18T10:16:31.261+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-08-18T10:16:31.261+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-08-18T10:16:31.262+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-08-18T10:16:31.262+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-08-18T10:16:31.263+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-08-18T10:16:31.263+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-08-18T10:16:31.264+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-08-18T10:16:31.264+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-08-18T10:16:31.265+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-08-18T10:16:31.265+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-08-18T10:16:31.265+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-08-18T10:16:31.266+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-08-18T10:16:31.266+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-08-18T10:16:31.266+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-08-18T10:16:31.267+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-08-18T10:16:31.267+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-08-18T10:16:31.268+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-08-18T10:16:31.268+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-08-18T10:16:31.268+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-08-18T10:16:31.269+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-08-18T10:16:31.269+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /storage/hdfs/processed/golden_dataset/part-00000-db1a0cbd-e62a-41da-949d-a5692fdcd3ed-c000.snappy.parquet
[2025-08-18T10:16:31.269+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-08-18T10:16:31.270+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-08-18T10:16:31.270+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
[2025-08-18T10:16:31.270+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1954)
[2025-08-18T10:16:31.270+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
[2025-08-18T10:16:31.271+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
[2025-08-18T10:16:31.271+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-08-18T10:16:31.271+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-08-18T10:16:31.272+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-08-18T10:16:31.272+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-08-18T10:16:31.272+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-08-18T10:16:31.272+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-08-18T10:16:31.273+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-08-18T10:16:31.273+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-08-18T10:16:31.274+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-08-18T10:16:31.274+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:31.274+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-08-18T10:16:31.275+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-08-18T10:16:31.275+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-08-18T10:16:31.275+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-08-18T10:16:31.275+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-08-18T10:16:31.276+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy31.getBlockLocations(Unknown Source)
[2025-08-18T10:16:31.276+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-08-18T10:16:31.276+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-08-18T10:16:31.277+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-08-18T10:16:31.277+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-08-18T10:16:31.277+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-08-18T10:16:31.277+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-08-18T10:16:31.278+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-08-18T10:16:31.278+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-08-18T10:16:31.278+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-08-18T10:16:31.278+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-08-18T10:16:31.279+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy32.getBlockLocations(Unknown Source)
[2025-08-18T10:16:31.279+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-08-18T10:16:31.280+0000] {subprocess.py:93} INFO - 	... 28 more
[2025-08-18T10:16:31.280+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:31.280+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-08-18T10:16:31.281+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-08-18T10:16:31.281+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-08-18T10:16:31.282+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-08-18T10:16:31.282+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-08-18T10:16:31.282+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-08-18T10:16:31.283+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-08-18T10:16:31.283+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-08-18T10:16:31.283+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-08-18T10:16:31.284+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-08-18T10:16:31.284+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-08-18T10:16:31.284+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-08-18T10:16:31.284+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-08-18T10:16:31.285+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-08-18T10:16:31.285+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-08-18T10:16:31.285+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-08-18T10:16:31.286+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-08-18T10:16:31.286+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2398)
[2025-08-18T10:16:31.286+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2419)
[2025-08-18T10:16:31.286+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2438)
[2025-08-18T10:16:31.287+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2463)
[2025-08-18T10:16:31.287+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1049)
[2025-08-18T10:16:31.287+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-08-18T10:16:31.288+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-08-18T10:16:31.288+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
[2025-08-18T10:16:31.288+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.collect(RDD.scala:1048)
[2025-08-18T10:16:31.288+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.mergeSchemasInParallel(SchemaMergeUtils.scala:74)
[2025-08-18T10:16:31.289+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.mergeSchemasInParallel(ParquetFileFormat.scala:497)
[2025-08-18T10:16:31.289+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetUtils$.inferSchema(ParquetUtils.scala:132)
[2025-08-18T10:16:31.289+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.inferSchema(ParquetFileFormat.scala:79)
[2025-08-18T10:16:31.290+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
[2025-08-18T10:16:31.290+0000] {subprocess.py:93} INFO - 	at scala.Option.orElse(Option.scala:447)
[2025-08-18T10:16:31.290+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
[2025-08-18T10:16:31.290+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:407)
[2025-08-18T10:16:31.291+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-08-18T10:16:31.291+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-08-18T10:16:31.291+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-08-18T10:16:31.292+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-08-18T10:16:31.292+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:563)
[2025-08-18T10:16:31.292+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-08-18T10:16:31.292+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-08-18T10:16:31.293+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-08-18T10:16:31.293+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-08-18T10:16:31.293+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-08-18T10:16:31.293+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-08-18T10:16:31.294+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-08-18T10:16:31.294+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-08-18T10:16:31.294+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-08-18T10:16:31.295+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-08-18T10:16:31.295+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-08-18T10:16:31.295+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-08-18T10:16:31.295+0000] {subprocess.py:93} INFO - Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-08-18T10:16:31.296+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-08-18T10:16:31.296+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-08-18T10:16:31.296+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:387)
[2025-08-18T10:16:31.296+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-08-18T10:16:31.297+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-08-18T10:16:31.297+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-08-18T10:16:31.297+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:80)
[2025-08-18T10:16:31.298+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:858)
[2025-08-18T10:16:31.298+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:858)
[2025-08-18T10:16:31.298+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-08-18T10:16:31.299+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-08-18T10:16:31.299+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-08-18T10:16:31.299+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-08-18T10:16:31.299+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-08-18T10:16:31.300+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-08-18T10:16:31.300+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-08-18T10:16:31.300+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-08-18T10:16:31.301+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-08-18T10:16:31.301+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-08-18T10:16:31.301+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-08-18T10:16:31.302+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-08-18T10:16:31.302+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-08-18T10:16:31.303+0000] {subprocess.py:93} INFO - 	... 1 more
[2025-08-18T10:16:31.303+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /storage/hdfs/processed/golden_dataset/part-00000-db1a0cbd-e62a-41da-949d-a5692fdcd3ed-c000.snappy.parquet
[2025-08-18T10:16:31.304+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-08-18T10:16:31.304+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-08-18T10:16:31.305+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
[2025-08-18T10:16:31.306+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1954)
[2025-08-18T10:16:31.307+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
[2025-08-18T10:16:31.307+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
[2025-08-18T10:16:31.307+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-08-18T10:16:31.308+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-08-18T10:16:31.308+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-08-18T10:16:31.308+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-08-18T10:16:31.309+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-08-18T10:16:31.309+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-08-18T10:16:31.309+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-08-18T10:16:31.310+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-08-18T10:16:31.310+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-08-18T10:16:31.310+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:31.310+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-08-18T10:16:31.311+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-08-18T10:16:31.311+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-08-18T10:16:31.311+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-08-18T10:16:31.312+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-08-18T10:16:31.312+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-08-18T10:16:31.313+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-08-18T10:16:31.313+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-08-18T10:16:31.313+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-08-18T10:16:31.313+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-08-18T10:16:31.314+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-08-18T10:16:31.314+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-08-18T10:16:31.314+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-08-18T10:16:31.314+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-08-18T10:16:31.315+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-08-18T10:16:31.315+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-08-18T10:16:31.315+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-08-18T10:16:31.316+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-08-18T10:16:31.316+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-08-18T10:16:31.316+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-08-18T10:16:31.316+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-08-18T10:16:31.317+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-08-18T10:16:31.317+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-08-18T10:16:31.317+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-08-18T10:16:31.318+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-08-18T10:16:31.318+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-08-18T10:16:31.318+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-08-18T10:16:31.319+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-08-18T10:16:31.319+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-08-18T10:16:31.320+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-08-18T10:16:31.321+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-08-18T10:16:31.322+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-08-18T10:16:31.323+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-08-18T10:16:31.323+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-08-18T10:16:31.323+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-08-18T10:16:31.323+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-08-18T10:16:31.324+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /storage/hdfs/processed/golden_dataset/part-00000-db1a0cbd-e62a-41da-949d-a5692fdcd3ed-c000.snappy.parquet
[2025-08-18T10:16:31.326+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-08-18T10:16:31.326+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-08-18T10:16:31.326+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
[2025-08-18T10:16:31.327+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1954)
[2025-08-18T10:16:31.327+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
[2025-08-18T10:16:31.327+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
[2025-08-18T10:16:31.328+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-08-18T10:16:31.328+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
[2025-08-18T10:16:31.328+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
[2025-08-18T10:16:31.328+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
[2025-08-18T10:16:31.329+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
[2025-08-18T10:16:31.329+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-08-18T10:16:31.329+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-08-18T10:16:31.330+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
[2025-08-18T10:16:31.330+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
[2025-08-18T10:16:31.330+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:31.330+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-08-18T10:16:31.331+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-08-18T10:16:31.331+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-08-18T10:16:31.331+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-08-18T10:16:31.332+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-08-18T10:16:31.332+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy31.getBlockLocations(Unknown Source)
[2025-08-18T10:16:31.332+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-08-18T10:16:31.332+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-08-18T10:16:31.333+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-08-18T10:16:31.333+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-08-18T10:16:31.333+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-08-18T10:16:31.334+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-08-18T10:16:31.334+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-08-18T10:16:31.334+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-08-18T10:16:31.335+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-08-18T10:16:31.335+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-08-18T10:16:31.335+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy32.getBlockLocations(Unknown Source)
[2025-08-18T10:16:31.336+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-08-18T10:16:31.336+0000] {subprocess.py:93} INFO - 	... 28 more
[2025-08-18T10:16:31.337+0000] {subprocess.py:93} INFO - 
[2025-08-18T10:16:31.337+0000] {subprocess.py:93} INFO - 25/08/18 10:16:31 INFO SparkContext: Invoking stop() from shutdown hook
[2025-08-18T10:16:31.338+0000] {subprocess.py:93} INFO - 25/08/18 10:16:31 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-08-18T10:16:31.375+0000] {subprocess.py:93} INFO - 25/08/18 10:16:31 INFO SparkUI: Stopped Spark web UI at http://4bf6b336ccb3:4041
[2025-08-18T10:16:31.400+0000] {subprocess.py:93} INFO - 25/08/18 10:16:31 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-08-18T10:16:31.404+0000] {subprocess.py:93} INFO - 25/08/18 10:16:31 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-08-18T10:16:31.872+0000] {subprocess.py:93} INFO - 25/08/18 10:16:31 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-08-18T10:16:32.126+0000] {subprocess.py:93} INFO - 25/08/18 10:16:32 INFO MemoryStore: MemoryStore cleared
[2025-08-18T10:16:32.142+0000] {subprocess.py:93} INFO - 25/08/18 10:16:32 INFO BlockManager: BlockManager stopped
[2025-08-18T10:16:32.384+0000] {subprocess.py:93} INFO - 25/08/18 10:16:32 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-08-18T10:16:32.498+0000] {subprocess.py:93} INFO - 25/08/18 10:16:32 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-08-18T10:16:32.662+0000] {subprocess.py:93} INFO - 25/08/18 10:16:32 INFO SparkContext: Successfully stopped SparkContext
[2025-08-18T10:16:32.669+0000] {subprocess.py:93} INFO - 25/08/18 10:16:32 INFO ShutdownHookManager: Shutdown hook called
[2025-08-18T10:16:32.677+0000] {subprocess.py:93} INFO - 25/08/18 10:16:32 INFO ShutdownHookManager: Deleting directory /tmp/spark-ccf20ae9-910e-4889-a4b5-e1cbdc950851
[2025-08-18T10:16:32.704+0000] {subprocess.py:93} INFO - 25/08/18 10:16:32 INFO ShutdownHookManager: Deleting directory /tmp/spark-65dad7b2-68ec-4c48-9c04-0406ac71ee0e
[2025-08-18T10:16:32.722+0000] {subprocess.py:93} INFO - 25/08/18 10:16:32 INFO ShutdownHookManager: Deleting directory /tmp/spark-65dad7b2-68ec-4c48-9c04-0406ac71ee0e/pyspark-f90980e1-f947-491e-9a82-f5b85cfa2685
[2025-08-18T10:16:33.319+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-18T10:16:33.322+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T10:16:33.357+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-18T10:16:33.374+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_simple, task_id=golden_to_star, execution_date=20250818T100546, start_date=20250818T101350, end_date=20250818T101633
[2025-08-18T10:16:33.406+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task golden_to_star (Bash command failed. The command returned a non-zero exit code 1.; 2133)
[2025-08-18T10:16:33.461+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T10:16:33.493+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T10:16:33.498+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
