[2025-08-18T08:06:23.146+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T08:06:23.211+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_exec.ingest_raw manual__2025-08-18T08:06:22.176080+00:00 [queued]>
[2025-08-18T08:06:23.228+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_exec.ingest_raw manual__2025-08-18T08:06:22.176080+00:00 [queued]>
[2025-08-18T08:06:23.228+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-08-18T08:06:23.255+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): ingest_raw> on 2025-08-18 08:06:22.176080+00:00
[2025-08-18T08:06:23.263+0000] {standard_task_runner.py:63} INFO - Started process 277 to run task
[2025-08-18T08:06:23.267+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_exec', 'ingest_raw', 'manual__2025-08-18T08:06:22.176080+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpno3lpoee']
[2025-08-18T08:06:23.270+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask ingest_raw
[2025-08-18T08:06:23.362+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_exec.ingest_raw manual__2025-08-18T08:06:22.176080+00:00 [running]> on host 545418c0948b
[2025-08-18T08:06:23.514+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_exec' AIRFLOW_CTX_TASK_ID='ingest_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T08:06:22.176080+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T08:06:22.176080+00:00'
[2025-08-18T08:06:23.515+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T08:06:23.548+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T08:06:23.549+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec youtube-pipeline-project_spark-master_1 spark-submit --packages org.apache.spark:spark-avro_2.12:3.5.1 /app/batch/ingestion/ingest_raw_to_hdfs.py']
[2025-08-18T08:06:23.567+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T08:06:23.586+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-08-18T08:06:23.587+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-18T08:06:23.589+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T08:06:23.613+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-18T08:06:23.619+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_exec, task_id=ingest_raw, execution_date=20250818T080622, start_date=20250818T080623, end_date=20250818T080623
[2025-08-18T08:06:23.644+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task ingest_raw (Bash command failed. The command returned a non-zero exit code 1.; 277)
[2025-08-18T08:06:23.683+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T08:06:23.741+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T08:06:23.750+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
